#include "src/game/envfx_snow.h"

const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_dead_head[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -48, -1, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head_dead_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt1),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt2),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt3),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt4),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt5),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt6),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_option_dead_head_hatless[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt1),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt2),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt3),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt4),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt5),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt6),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_armature_002_switch_option_002[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -48, -1, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6),
			GEO_BRANCH(1, pipecrawler_002_switch_option_dead_head_hatless),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_right_hand_open_armature[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, -43, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 127, 0, 0, pipecrawler_002_switch_option_right_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_left_hand_open_armature[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 127, 0, 0, pipecrawler_002_switch_option_left_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_left_hand_peace_armature[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 127, 0, 0, pipecrawler_004_switch_option_left_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_left_hand_cap_armature[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 127, 0, 0, pipecrawler_005_switch_option_left_hand_cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_005_switch_option_left_hand_cap_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_left_hand_wing_cap_armature[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 127, 0, 0, pipecrawler_006_switch_option_left_hand_wing_cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_006_switch_option_left_hand_wing_cap_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_006_switch_option_left_hand_wing_cap_wings_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_dead_head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -48, -1, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt1),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt2),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt3),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt4),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt5),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt6),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7_switch_face_opt7),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_armature_002_switch_option_002_jump_pipecrawler_002_switch_option_dead_head_hatless[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt1),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt2),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt3),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt4),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt5),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt6),
			GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -48, -1, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_armature_002_switch_option_002_jump_pipecrawler_002_switch_option_dead_head_hatless),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, -43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, 0, 0, pipecrawler_002_switch_option_right_hand_open_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, 0, 0, pipecrawler_002_switch_option_left_hand_open_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, 0, 0, pipecrawler_004_switch_option_left_hand_peace_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, 0, 0, pipecrawler_005_switch_option_left_hand_cap_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_005_switch_option_left_hand_cap_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, 0, 0, pipecrawler_006_switch_option_left_hand_wing_cap_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_006_switch_option_left_hand_wing_cap_mesh_layer_5),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_006_switch_option_left_hand_wing_cap_wings_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 248, -1, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pipecrawler_000_offset_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 64, 0, 0, pipecrawler_000_offset_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_offset_001_mesh_layer_5),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 238, 24, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1),
											GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2),
											GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3),
											GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4),
											GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5),
											GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6),
											GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_dead_head),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 44, -117, -106, 16, -31, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_001_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 44, -117, 106, -16, 31, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_002_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 182, -32, 106, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pipecrawler_000_offset_003_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 169, -5, -24, pipecrawler_000_offset_004_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 175, 2, 10, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_003_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_right_hand_open_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 183, -32, -106, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pipecrawler_000_offset_006_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 169, -5, 24, pipecrawler_000_offset_007_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 175, 2, -10, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_004_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, -29, -3, 44, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_left_hand_open_armature),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_left_hand_peace_armature),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_left_hand_cap_armature),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1_jump_pipecrawler_left_hand_wing_cap_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 4, -12, 59, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pipecrawler_000_offset_009_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 171, -4, 4, pipecrawler_000_offset_010_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 181, 0, 2, pipecrawler_000_offset_011_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 4, -12, -59, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pipecrawler_000_offset_012_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 171, -4, -4, pipecrawler_000_offset_013_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 181, 0, -2, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_005_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_dead_head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -48, -1, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_metal_v3_001_0),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_metal_v3_001_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_armature_002_switch_option_002_jump_pipecrawler_002_switch_option_dead_head_hatless[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_metal_v3_001_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_metal_v3_001_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -48, -1, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_metal_v3_001_0),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_metal_v3_001_0),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_armature_002_switch_option_002_jump_pipecrawler_002_switch_option_dead_head_hatless),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, -43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 127, 0, 0, pipecrawler_002_switch_option_right_hand_open_mesh_layer_1_mat_override_metal_v3_001_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 127, 0, 0, pipecrawler_002_switch_option_left_hand_open_mesh_layer_1_mat_override_metal_v3_001_0),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 127, 0, 0, pipecrawler_004_switch_option_left_hand_peace_mesh_layer_1_mat_override_metal_v3_001_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 127, 0, 0, pipecrawler_005_switch_option_left_hand_cap_mesh_layer_1_mat_override_metal_v3_001_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_005_switch_option_left_hand_cap_mesh_layer_5_mat_override_metal_v3_001_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 127, 0, 0, pipecrawler_006_switch_option_left_hand_wing_cap_mesh_layer_1_mat_override_metal_v3_001_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_006_switch_option_left_hand_wing_cap_mesh_layer_5_mat_override_metal_v3_001_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_006_switch_option_left_hand_wing_cap_wings_mesh_layer_5_mat_override_metal_v3_001_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 248, -1, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pipecrawler_000_offset_mesh_layer_1_mat_override_metal_v3_001_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, pipecrawler_000_offset_001_mesh_layer_1_mat_override_metal_v3_001_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_offset_001_mesh_layer_5_mat_override_metal_v3_001_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 238, 24, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_mesh_layer_1_mat_override_metal_v3_001_0),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_metal_v3_001_0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_dead_head),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 44, -117, -106, 16, -31, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_001_mesh_layer_5_mat_override_metal_v3_001_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 44, -117, 106, -16, 31, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_002_mesh_layer_5_mat_override_metal_v3_001_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 182, -32, 106, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pipecrawler_000_offset_003_mesh_layer_1_mat_override_metal_v3_001_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 169, -5, -24, pipecrawler_000_offset_004_mesh_layer_1_mat_override_metal_v3_001_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 175, 2, 10, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_003_mesh_layer_1_mat_override_metal_v3_001_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_right_hand_open_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 183, -32, -106, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pipecrawler_000_offset_006_mesh_layer_1_mat_override_metal_v3_001_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 169, -5, 24, pipecrawler_000_offset_007_mesh_layer_1_mat_override_metal_v3_001_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 175, 2, -10, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_004_mesh_layer_1_mat_override_metal_v3_001_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, -29, -3, 44, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_left_hand_open_armature),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_left_hand_peace_armature),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_left_hand_cap_armature),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt2_jump_pipecrawler_left_hand_wing_cap_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 4, -12, 59, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pipecrawler_000_offset_009_mesh_layer_1_mat_override_metal_v3_001_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 171, -4, 4, pipecrawler_000_offset_010_mesh_layer_1_mat_override_metal_v3_001_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 181, 0, 2, pipecrawler_000_offset_011_mesh_layer_1_mat_override_metal_v3_001_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 4, -12, -59, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pipecrawler_000_offset_012_mesh_layer_1_mat_override_metal_v3_001_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 171, -4, -4, pipecrawler_000_offset_013_mesh_layer_1_mat_override_metal_v3_001_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 181, 0, -2, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_005_mesh_layer_1_mat_override_metal_v3_001_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_dead_head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -48, -1, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_1_mat_override_metal_v3_001_0),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head_dead_mesh_layer_5_mat_override_metal_v3_001_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_armature_002_switch_option_002_jump_pipecrawler_002_switch_option_dead_head_hatless[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_1_mat_override_metal_v3_001_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_002_switch_option_head_dead_no_cap_mesh_layer_5_mat_override_metal_v3_001_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -48, -1, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_1_mat_override_metal_v3_001_0),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_002_switch_option_head__no_cap__mesh_layer_5_mat_override_metal_v3_001_0),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_armature_002_switch_option_002_jump_pipecrawler_002_switch_option_dead_head_hatless),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, -43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, 0, 0, pipecrawler_002_switch_option_right_hand_open_mesh_layer_1_mat_override_metal_v3_001_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, 0, 0, pipecrawler_002_switch_option_left_hand_open_mesh_layer_1_mat_override_metal_v3_001_0),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, 0, 0, pipecrawler_004_switch_option_left_hand_peace_mesh_layer_1_mat_override_metal_v3_001_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, 0, 0, pipecrawler_005_switch_option_left_hand_cap_mesh_layer_1_mat_override_metal_v3_001_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_005_switch_option_left_hand_cap_mesh_layer_5_mat_override_metal_v3_001_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, -3, 43, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, 0, 0, pipecrawler_006_switch_option_left_hand_wing_cap_mesh_layer_1_mat_override_metal_v3_001_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_006_switch_option_left_hand_wing_cap_mesh_layer_5_mat_override_metal_v3_001_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_006_switch_option_left_hand_wing_cap_wings_mesh_layer_5_mat_override_metal_v3_001_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 248, -1, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pipecrawler_000_offset_mesh_layer_1_mat_override_metal_v3_001_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 64, 0, 0, pipecrawler_000_offset_001_mesh_layer_1_mat_override_metal_v3_001_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_offset_001_mesh_layer_5_mat_override_metal_v3_001_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 238, 24, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_1_mat_override_metal_v3_001_0),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_metal_v3_001_0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_dead_head),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 44, -117, -106, 16, -31, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_001_mesh_layer_5_mat_override_metal_v3_001_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 44, -117, 106, -16, 31, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_002_mesh_layer_5_mat_override_metal_v3_001_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 182, -32, 106, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pipecrawler_000_offset_003_mesh_layer_1_mat_override_metal_v3_001_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 169, -5, -24, pipecrawler_000_offset_004_mesh_layer_1_mat_override_metal_v3_001_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 175, 2, 10, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_003_mesh_layer_1_mat_override_metal_v3_001_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_right_hand_open_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 183, -32, -106, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pipecrawler_000_offset_006_mesh_layer_1_mat_override_metal_v3_001_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 169, -5, 24, pipecrawler_000_offset_007_mesh_layer_1_mat_override_metal_v3_001_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 175, 2, -10, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_004_mesh_layer_1_mat_override_metal_v3_001_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, -29, -3, 44, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_left_hand_open_armature),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_left_hand_peace_armature),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_left_hand_cap_armature),
										GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt3_jump_pipecrawler_left_hand_wing_cap_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 4, -12, 59, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pipecrawler_000_offset_009_mesh_layer_1_mat_override_metal_v3_001_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 171, -4, 4, pipecrawler_000_offset_010_mesh_layer_1_mat_override_metal_v3_001_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 181, 0, 2, pipecrawler_000_offset_011_mesh_layer_1_mat_override_metal_v3_001_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 4, -12, -59, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, pipecrawler_000_offset_012_mesh_layer_1_mat_override_metal_v3_001_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 171, -4, -4, pipecrawler_000_offset_013_mesh_layer_1_mat_override_metal_v3_001_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 181, 0, -2, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_005_mesh_layer_1_mat_override_metal_v3_001_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pipecrawler_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),

			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 248, -1, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pipecrawler_000_offset_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, pipecrawler_000_offset_001_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_offset_001_mesh_layer_5),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 238, 24, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_mesh_layer_1),
																		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_mesh_layer_5),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1),
																	GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2),
																	GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3),
																	GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4),
																	GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5),
																	GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6),
																	GEO_BRANCH(1, pipecrawler_dead_head),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, pipecrawler_armature_002_switch_option_002),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 44, -117, -106, 16, -31, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_001_mesh_layer_5),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 44, -117, 106, -16, 31, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_000_displaylist_002_mesh_layer_5),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 182, -32, 106, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pipecrawler_000_offset_003_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 169, -5, -24, pipecrawler_000_offset_004_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 175, 2, 10, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_003_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, pipecrawler_right_hand_open_armature),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 183, -32, -106, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pipecrawler_000_offset_006_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 169, -5, 24, pipecrawler_000_offset_007_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 175, 2, -10, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_004_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, -29, -3, 44, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, pipecrawler_left_hand_open_armature),
																GEO_BRANCH(1, pipecrawler_left_hand_peace_armature),
																GEO_BRANCH(1, pipecrawler_left_hand_cap_armature),
																GEO_BRANCH(1, pipecrawler_left_hand_wing_cap_armature),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 4, -12, 59, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pipecrawler_000_offset_009_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 171, -4, 4, pipecrawler_000_offset_010_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 181, 0, 2, pipecrawler_000_offset_011_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 4, -12, -59, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pipecrawler_000_offset_012_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 171, -4, -4, pipecrawler_000_offset_013_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 181, 0, -2, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_000_displaylist_005_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt1),
							GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt2),
							GEO_BRANCH(1, pipecrawler_002_switch_opt0_001_switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pipecrawler_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pipecrawler_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
